---
- hosts: web_servers
  become: true
  tasks:
    - name: Print OS info
      package:
        name: httpd
      register: package_result

    - name: Debug package result
      debug:
        var: package_result
